# Generated by Django 4.0.2 on 2022-04-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_taken',
            name='course2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
