# Generated by Django 4.0.2 on 2022-04-15 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_courses_taken_course10_courses_taken_course3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='class',
            name='form',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='faculty',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='class_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.form'),
        ),
    ]
