# Generated by Django 4.0.2 on 2022-04-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_form_remove_class_form_remove_departments_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Engr.'), (4, 'Prof.'), (5, 'Ms.')], default=0)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Head of Department',
                'verbose_name_plural': 'Head of Departments',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='departments',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.hod'),
        ),
    ]
