# Generated by Django 4.0.2 on 2022-04-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_hod_alter_departments_hod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
    ]
