# Generated by Django 4.0.2 on 2022-04-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_studentdata_options_teachersecondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.student_field'),
        ),
    ]
