# Generated by Django 4.0.2 on 2022-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_allcourses_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprimary',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teachersecondary',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
