# Generated by Django 4.0.2 on 2022-04-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Engr.'), (4, 'Prof.'), (5, 'Ms.')], default=0, null=True),
        ),
    ]
