# Generated by Django 4.0.2 on 2022-04-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_customuser_status_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='student_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
