# Generated by Django 4.0.2 on 2022-04-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_studentdata_student_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdata',
            options={'verbose_name': 'student datum', 'verbose_name_plural': 'students data'},
        ),
    ]
