# Generated by Django 4.0.2 on 2022-04-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_studentdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdata',
            options={},
        ),
    ]
