# Generated by Django 4.0.2 on 2022-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_studentdata_options_alter_studentdata_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdata',
            name='staff_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
