# Generated by Django 4.0.2 on 2022-04-22 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_staffdata_staff_image_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.staffdata')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherprimary',
            name='class_form',
        ),
        migrations.RemoveField(
            model_name='teacherprimary',
            name='class_handled',
        ),
        migrations.RemoveField(
            model_name='teacherprimary',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='teacherprimary',
            name='staff_details',
        ),
        migrations.RemoveField(
            model_name='teacherprimary',
            name='subjects_taught',
        ),
        migrations.RemoveField(
            model_name='teachersecondary',
            name='class_handled',
        ),
        migrations.RemoveField(
            model_name='teachersecondary',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='teachersecondary',
            name='staff_details',
        ),
        migrations.RemoveField(
            model_name='teachersecondary',
            name='subjects_taught',
        ),
        migrations.DeleteModel(
            name='Courses_taken',
        ),
        migrations.DeleteModel(
            name='Teacherprimary',
        ),
        migrations.DeleteModel(
            name='TeacherSecondary',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='teacher_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.teachers'),
        ),
    ]
