# Generated by Django 4.0.2 on 2022-04-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_teachers_remove_teacherprimary_class_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='study_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.student_field'),
        ),
    ]
