# Generated by Django 4.0.2 on 2022-04-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_studentdata_study_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
