# Generated by Django 4.0.2 on 2022-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_teachers_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
