# Generated by Django 4.0.2 on 2022-04-22 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_teachers_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='tic_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
