# Generated by Django 4.0.2 on 2022-04-23 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
