# Generated by Django 4.0.2 on 2022-05-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_admissionapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdmissionApp',
            new_name='Apply',
        ),
    ]
