# Generated by Django 4.0.2 on 2022-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_rename_admissionapp_apply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'ordering': ['firstname'], 'verbose_name': 'Admission Application', 'verbose_name_plural': 'Admission Applications'},
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='class_name',
            new_name='class_choice',
        ),
        migrations.AddField(
            model_name='apply',
            name='Admitted',
            field=models.BooleanField(default=False),
        ),
    ]
