# Generated by Django 4.0.2 on 2022-05-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_alter_apply_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
