# Generated by Django 4.0.2 on 2022-05-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_alter_apply_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='admitted',
        ),
    ]
