# Generated by Django 4.0.2 on 2022-04-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialuser',
            name='is_man',
            field=models.BooleanField(default=True),
        ),
    ]
