# Generated by Django 4.0.2 on 2022-05-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_trialuser_is_man'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialuser',
            old_name='is_man',
            new_name='is_admitted',
        ),
    ]
